### ISSUE TITLE
sat-stac vs pystac

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/intake-stac#43]
I see this uses [sat-stac](https://github.com/sat-utils/sat-stac), but isn't the COG gang mostly using [pystac](https://github.com/azavea/pystac) now?    Or doesn't it matter for this application?
ping @matthewhanson

**Comment by jhamman** [comment]
The short answer is that we started work on Intake-stac before pystac began development (https://github.com/azavea/pystac/commit/1fe88114bb30fc58692d77a92e8e08b80ad47ef8). @matthewhanson and I have talked a bit about the future of sat-stac but for now, we have sat-stac as a dependency. If there was interest, we could explore adding pystac support (either as a replacement for or in addition to sat-stac.

**Comment by rsignell-usgs** [comment]
Thanks for the explanation @jhamman!

**Comment by scottyhq** [comment]
I'm going to reopen this since I think it'll be relevant in the coming months as the STAC spec approaches a 1.0 release:
https://medium.com/radiant-earth-insights/stac-0-9-0-release-our-final-major-release-before-1-0-beta-17467953e45e

We should probably keep the dependencies of intake-stac limited to one or the other.

**Comment by scottyhq** [comment]
closed by #72
